#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Uncomment and modify the following lines if you want to log access
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';
    #access_log  logs/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Proxy common settings
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;

    # HTTPS server
    server {
        listen       443 ssl;
        server_name  192.168.43.218;

        # SSL certificate configuration using the provided pem and key files.
        ssl_certificate      "C:/Users/Cris-SX/Desktop/UA/TFG/CERTIFICADOS/v2/server_cert.pem";
        ssl_certificate_key  "C:/Users/Cris-SX/Desktop/UA/TFG/CERTIFICADOS/v2/server_key.pem";
        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;

        # Routing for WARs and the Spring Boot app

        # Redirige peticiones que comiencen con /vital-sanity/afirma-signature-storage/ o
        # /vital-sanity/afirma-signature-retriever/ hacia el Tomcat externo (HTTPS en puerto 8080)
        location ~ ^/vital-sanity/(afirma-signature-storage|afirma-signature-retriever|afirma-server-triphase-signer)/ {
            proxy_pass https://localhost:8080;
        }

        # Redirige el resto de las peticiones de /vital-sanity/ hacia la aplicacion Spring Boot (HTTPS en puerto 8762)
        location /vital-sanity/ {
            proxy_pass https://localhost:8058;
        }

        # Opcionalmente puedes definir mas reglas o personalizar las respuestas de error
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

    # Si es necesario se pueden configurar otros virtual hosts aqui.
}
